In [ ]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
y = np.ones(np.shape(x), dtype=np.int64)
print(x,y)

[0 1 2 3] [1 1 1 1]

Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
X = np.array([[1, 2], [3, 4]])
X= np.matrix(X)
print(X)

[[1 2]
 [3 4]]

Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
X=np.arange(3,10,0.14,dtype=float)
print(X)

[3.   3.14 3.28 3.42 3.56 3.7  3.84 3.98 4.12 4.26 4.4  4.54 4.68 4.82
 4.96 5.1  5.24 5.38 5.52 5.66 5.8  5.94 6.08 6.22 6.36 6.5  6.64 6.78
 6.92 7.06 7.2  7.34 7.48 7.62 7.76 7.9  8.04 8.18 8.32 8.46 8.6  8.74
 8.88 9.02 9.16 9.3  9.44 9.58 9.72 9.86]

Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
X= ([[1,2,3],[4,5,6]])
X=np.dstack(X).ravel()
print(X)

[1 4 2 5 3 6]

Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x=np.arange(1,10,1,dtype=int).reshape(3,3)
x=(np.hsplit(x,3))
print(x)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]

 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [ ]:
x=[[1,2],[3,4]]
s=np.trace(x)
print(s)

5

Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [ ]:
x=np.array([[1,4], [3,1]])
x.sort(axis=1)
print(x)

[[1 4]
 [1 3]]

Q8 Get the indices that would sort x(as above) along the second axis.

In [ ]:
x=np.array([[1,4], [3,1]])
print(np.argsort(x,axis=1))

[[0 1]
 [1 0]]

Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
import random
x=np.array(random.choices(range(0,10),k=10)).reshape(2,5)
print(x)
xmin,xmax=x.min(),x.max()
print(np.argmax(x),np.argmin(x))

[[5 2 5 4 2]
 [2 4 8 6 2]]
7 1

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value.

Find the correlation between first two columns.

Find the mean,median and standard deviation of column 3.

Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

Find the most frequent value of petal length (3rd column) in iris dataset